import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "./ClientProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthContext from "@/conttext/AuthContext";

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
  icons: ""
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <ClientProvider>
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </ClientProvider>
        </AuthContext>

      </body>
    </html>
  );
}
