import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/conttext/AuthContext";
import ClientProvider from "./ClientProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
  icons: ""
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ClientProvider>
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </ClientProvider>
        </AuthProvider>

      </body>
    </html>
  );
}
